#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd > /tmp/sxhkd.log 2>&1 &
pgrep -x picom > /dev/null || picom -b --vsync --backend glx &
feh --bg-fill ~/Pictures/Wallpapers/2/Colors.png

# Java fix: https://www.reddit.com/r/bspwm/comments/267srd/problem_with_intellij_bspwm/
wmname LG3D

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           4 
bspc config top_padding          24
bspc config left_padding         0 
bspc config focused_border_color \#bababa
#bspc config focused_border_color \#00557f

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config click_to_focus       any
#bspc config swallow_first_click  true
#bspc config ignore_ewmh_focus    true

bspc config external_rules_command /home/wmatex/.local/bin/bspwm_external_rules
bspc rule -a mpv state=floating

# Plasma
bspc rule -a systemsettings state=floating private=on center=off
bspc rule -a plasmashell border=off state=floating private=on center=off
bspc rule -a Plasma manage=off border=off state=floating
bspc rule -a plasma-desktop manage=off border=off state=floating
bspc rule -a krunner border=off state=floating
bspc rule -a jetbrains-phpstorm center=off
bspc rule -a Sxiv state=floating

# Scratchpad
bspc rule -a Slack sticky=on state=floating 
bspc rule -a Spotify sticky=on state=floating border=off
